services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml:ro
      - ./prometheus/data:/prometheus
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana-oss 
    ports:
      - 9091:3000
    volumes:
      - ./grafana/data:/var/lib/grafana
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
      - ./grafana/dashboards:/etc/dashboards:ro
    environment:
      GF_PATHS_PROVISIONING: /etc/grafana/provisioning

